version: "3.8"

name: mails

services:
  postgres:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file: .env

  redis:
    image: redis
    volumes:
      - redis_data:/redis/data
    ports:
      - "6379:6379"
    env_file: .env

  app:
    build:
      context: ../
      dockerfile: ./deployment/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/opt/app/
    depends_on:
      - postgres
      - redis
    env_file: .env

volumes:
  postgres_data:
  redis_data:
